TylerHendricks-Web/Areas/AdminPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TylerHendricks_Core.Models;
using TylerHendricks_Repo.Contracts;
using TylerHendricks_Utility;
using TylerHendricks_Web.Claim;
using TylerHendricks_Web.Filters;

using static TylerHendricks_Utility.Enums.Areas;

namespace TylerHendricks_Web.Areas.AdminPortal.Controllers
{
    [Area("AdminPortal")]
    public class HomeController : Controller
    {
        private readonly IUsers _userManager;
        private readonly IEmailProvider _email;
        private readonly IUserService _userService;
        private readonly IRepositoryCollection _repCollection;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ILogger<HomeController> _logger;
        private readonly ResourcesConfig _resourcesConfig;
        private readonly EnvironmentalResource _environmentalResource;

        public HomeController(IUsers userManager, IEmailProvider email, IRepositoryCollection repositoryCollection, IUserService
     userService, IWebHostEnvironment hostingEnvironment, ILogger<HomeController> logger, ResourcesConfig resourcesConfig
            ,EnvironmentalResource environmentalResource)
        {
            _userManager = userManager;
            _email = email;
            _repCollection = repositoryCollection;
            _userService = userService;
            _hostingEnvironment = hostingEnvironment;
            _logger = logger;
            _resourcesConfig = resourcesConfig;
            _environmentalResource = environmentalResource;
        }

        #region [User Handler]
        [HttpGet]
        [AllowAnonymous]
        [Route("admin-portal")]
        [ServiceFilter(typeof(CustomLoginedUserAuthentication))]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("admin-portal")]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                loginModel.Role = RoleType.Admin.ToString();
                LoginType loginType = await _userManager.SignIn(loginModel).ConfigureAwait(true);
                if (loginType == LoginType.Success)
                {
                    return RedirectToAction(nameof(PatientInfo), "Home", new { area = PortalType.AdminPortal.ToString() });
                }
                else if (loginType == LoginType.WrongPassword)
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                    return View();
                }
                else
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                return View();
            }
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("admin-portal/ForGotPassword")]
        public IActionResult ForGotPassword()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("admin-portal/ForGotPassword")]
        public async Task<IActionResult> ForGotPassword(ForgotModel resetPassword)
        {
            ActionResult action;
            if (ModelState.IsValid)
            {
                resetPassword.Role = RoleType.Admin.ToString();
                PasswordToken passToken = await _userManager.ResetPasswordToken(resetPassword).ConfigureAwait(true);
                if (passToken != null)
                {
                    var PassworfLink = Url.Action(nameof(ResetPassword), "Home", new { area = PortalType.AdminPortal.ToString(), TokenId = passToken.Id, Token = passToken.Token }, Request.Scheme);
                    var htmlbody = await _repCollection.AmazonCustom.GetTemplate
                        ( $"{_environmentalResource.AWSS3Credentials.EmailTemplateDirectory}/{EmailTemplate.ResetPassword.ToString()}.html" 
                        ,_environmentalResource.AWSS3Credentials.BucketName
                        ,_environmentalResource.AWSS3Credentials.AccessKeyId
                        ,_environmentalResource.AWSS3Credentials.SecretAccessKey
                        ).ConfigureAwait(true);
                    List<KeyValuePair<string, string>> placeHolders = new List<KeyValuePair<string, string>>() { new KeyValuePair<string, string>("{{ResetLink}}", PassworfLink) };
                    string body = Comman.UpdatePaceHolder(htmlbody, placeHolders);
                    _email.PlaintTextGmail(EmailTemplate.ResetPassword.ToString(), resetPassword.Email, _resourcesConfig.ResetPasswordEmailSubject, body);
                    TempData["alert"] = AlertType.ForgotPassword;
                    return action = RedirectToAction(nameof(Login));
                }
                else
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForUsername);
                    return View();
                }
            }
            else
            {
                return action = RedirectToAction(nameof(ForGotPassword));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ResetPassword(string TokenId, string Token)
        {
            if (string.IsNullOrEmpty(TokenId) || string.IsNullOrEmpty(Token))
            {
                return RedirectToAction(nameof(ForGotPassword), "Home", new { area = PortalType.AdminPortal.ToString() });
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> ResetPassword(ResetPasswordModel resetPassModel)
        {
            ActionResult action;
            if (ModelState.IsValid)
            {
                var IsSuccess = await _userManager.ResetPassword(resetPassModel).ConfigureAwait(true);
                TempData["alert"] = AlertType.ResetPassword;
                if (IsSuccess.Succeeded)
                {
                    action = RedirectToAction(nameof(Login));
                }
                else
                {
                    action = RedirectToAction(nameof(ResetPassword));
                }
            }
            else
            {
                action = RedirectToAction(nameof(ResetPassword));
            }
            return action;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> LogOut()
        {
            await _userManager.SignOut().ConfigureAwait(true);
            return RedirectToAction(nameof(Login), "Home", new { area = PortalType.AdminPortal.ToString() });
        }
        #endregion

        #region [State]

        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> State()
        {
            try
            {
                var serviceStates = await _repCollection.Admin.GetStates().ConfigureAwait(true);
                return View(serviceStates);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveState(int stateId)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false  };
            try
            {
                var result = await _repCollection.Admin.ChangeStateStatus(stateId).ConfigureAwait(true);
                if (result.Succeeded)
                {
                    ajaxResponse.Succeeded = true;
                }
            }
            catch (Exception ex)
            {
                ajaxResponse.Succeeded = false;
                ajaxResponse.ErrorMessage = ex.Message;
            }
            return Json(ajaxResponse);
        }

        #endregion

        #region [Notification]
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Notification()
        {
            try
            {
                var notifications = await _repCollection.Admin.GetNotifications().ConfigureAwait(true);
                return View(notifications);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveNotification(int id)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false };
            try
            {
                var result = await _repCollection.Admin.ChangeNotificationStatus(id).ConfigureAwait(true);
                if (result.Succeeded)
                {
                    ajaxResponse.Succeeded = true;
                }
            }
            catch (Exception ex)
            {
                ajaxResponse.Succeeded = false;
                ajaxResponse.ErrorMessage = ex.Message;
            }
            return Json(ajaxResponse);
        }
        #endregion

        #region [Consultation]
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Consultation()
        {
            try
            {
                var consultations =  await _repCollection.Admin.GetConsultations().ConfigureAwait(true);
                return View(consultations);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveConsultation(int id)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false };
            try
            {

TylerHendricks-Web/Areas/ViewComponents/HeaderPhysicianViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TylerHendricks_Repo.Contracts;
using TylerHendricks_Web.Claim;

namespace TylerHendricks_Web.Areas.ViewComponents
{
    public class HeaderPhysicianViewComponent: ViewComponent
    {
        #region Initialize private field
        private readonly IRepositoryCollection _repoCollection;
        private readonly IUserService _userService;
        private readonly IUsers _userManager;
        #endregion
        public HeaderPhysicianViewComponent(IRepositoryCollection repoCollection, IUserService userService, IUsers userManager)
        {
            _repoCollection = repoCollection;
            _userService = userService;
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync(bool StaticHeading, string HeadingText)
        {
            ViewBag.StaticHeading = StaticHeading;
            ViewBag.HeadingText = HeadingText;
            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                ViewBag.UserName = await _userManager.GetName(User.Identity.Name).ConfigureAwait(true);
            }      
            return View();
        }
    }
}

TylerHendricks-Web/Areas/ViewComponents/PhysicianRecordViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TylerHendricks_Core.Models;
using TylerHendricks_Repo.Contracts;
using TylerHendricks_Web.Claim;

namespace TylerHendricks_Web.Areas.ViewComponents
{
    public class PhysicianRecordViewComponent:ViewComponent
    {
        private readonly IRepositoryCollection _repositoryCollection;
        private readonly IUserService _userService;
        private readonly IUsers _userManager;
        public PhysicianRecordViewComponent(IRepositoryCollection repositoryCollection, IUserService userService, IUsers userManager)
        {
            _repositoryCollection = repositoryCollection;
            _userService = userService;
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync(int RecordType, string RecordText, string Class)
        {
            ViewBag.RecordCount = 0;
            ViewBag.RecordType = RecordType;
            ViewBag.RecordHeading = RecordText;
            ViewBag.Class = Class;
            var StateId = await _userManager.GetStateId(_userService.GetUserId()).ConfigureAwait(true);
            var timeZoneConfig = new TimeZoneConfig() { OffSet = -330, IsDayLightSaving = false };
            if (RecordType != 8)
            {
                var records = await _repositoryCollection.Physician.GetInformationModels(RecordType, StateId, timeZoneConfig, "", "", "", 10, 0, 0).ConfigureAwait(true);
                if (records != null)
                {
                    if (records.Count > 0)
                    {
                        ViewBag.RecordCount = records[0].TotalRows;
                    }
                    else
                    {
                        ViewBag.RecordCount = records.Count;
                    }
                }
            }
            else
            {
                var records = await _repositoryCollection.Physician.GetNotify().ConfigureAwait(true);
                if (records != null)
                {
                    ViewBag.RecordCount = records.Count;
                }
            }
            return View();
        }

        public IViewComponentResult PatientChartTab()
        {
            return View();
        }
    }
}

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/ForGotPassword.cshtml
@model ForgotModel
@{
    ViewData["Title"] = "Fogot Password";
}
<div id="UpdateContentDiv" style="width:100%">
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section class="col-12">
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6">
                    <img src="/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Forgot Password</h3>
                        <form method="post">
                            <div class="form-group">
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i><input asp-for="Email" class="form-control br-0" type="text" />
                                </div>
                                <label>Email Address</label>
                            </div>
                            <button type="submit" class="btn btn-theme btn-block">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section Scripts
{
    <script src="~/JS/Login.js?v=1.0.0.0"></script>
}

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h2>Phyiscan portal</h2>

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/Login.cshtml
@model LoginModel
@{
    ViewData["Title"] = "Physician Login";
}
<div id="UpdateContentDiv" class="w-100">
    @await Component.InvokeAsync("HeaderPhysician", new { StaticHeading = false, HeadingText = "PROVIDER PORTAL" })
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section class="col-12">
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6" style="margin-top:8px;">
                    <img src="/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Physician Log In</h3>
                        <form method="post">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i><input asp-for="Email" class="form-control br-0" type="text" />
                                </div>
                                <label>Email Address</label>
                            </div>
                            <div class="form-group">
                                <div class="inputControl position-relative">
                                    <i class="fa fa-lock position-absolute" aria-hidden="true"></i><input asp-for="Password" class="form-control br-0" type="password" />
                                </div>
                                <label>Password</label>
                            </div>
                            <input type="hidden" asp-for="TimezoneOffSet" id="hdnTimeZone">
                            <input type="hidden" asp-for="IsDayLightSaving" id="hdnDayLightSaving" />
                            <button type="submit" onclick="SetTimeZone();" class="btn btn-theme btn-block">Log In</button>
                            <a asp-action="ForGotPassword" asp-controller="Home" asp-area="PhysicianPortal">Forgot your password?</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    <script src="~/JS/Login.js?v=1.0.0.1"></script>
}

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/PatientChart.cshtml
@{
    ViewData["Title"] = "Patient Chart";
}

@await Component.InvokeAsync("HeaderPhysician", new { StaticHeading = true, HeadingText = "PATIENT CHART" })
<section class="pr-portal col-md-12 bg-white" id="PatientChart">
    <partial name="_PatientChart">
</section>

@section Scripts
{
    <script src="~/JS/PatientChart.js?v=1.1.0.7"></script>
}

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/PhysicianDashboard.cshtml
@{
    ViewData["Title"] = "Physician Dashboard";
}
<div id="UpdateContentDiv" class="w-100">
    @await Component.InvokeAsync("HeaderPhysician", new { StaticHeading = true, HeadingText = "PHYSICIAN DASHBOARD"})
    <div class="container-fluid topTab">
        <div class="row res-1">
            <div class="col-md-6 pl-0" style="margin-top:5px;">
                <div class="row">
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 1, RecordText = "Ready to prescribe", Class="k3" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 2, RecordText = "Further review needed", Class = "k1" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 3, RecordText = "Pending response", Class = "k1" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 4, RecordText = "All patients", Class = "k1" })
                </div>
            </div>
            <div class="col-md-6 pr-0" style="margin-top:5px;">
                <div class="row">
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 5, RecordText = "Denied", Class = "k1" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 6, RecordText = "Potential duplicates", Class = "k1" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 7, RecordText = "Responded", Class = "k1" })
                    @await Component.InvokeAsync("PhysicianRecord", new { RecordType = 8, RecordText = "Not currently servicing your area", Class = "k1" })
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12 mt-4 p-0">
                <div class="input-group ">
                    <div class="input-group-prepend searchBg">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" id="txtSearch" class="form-control br-0" placeholder="Type of search">
                </div>
            </div>
        </div>
    </div>
    <section class="container-fluid topTab">
        <div class="table-responsive" style="margin-left:-16px;width:103%;overflow:hidden">
            <table class="table table-style" id="tblPatientDashboard" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Patient Name</th>
                        <th>Service Type</th>
                        <th>DOB</th>
                        <th>State</th>
                        <th>Submitted</th>
                        <th>Requested Rx</th>
                        <th>Refills Requested</th>
                        <th>Status</th>
                        <th>Wait in Queue</th>
                       
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <table class="table table-style" id="tblPatientNotifyDashboard" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>SNo</th>
                        <th>Email</th>
                        <th>State</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </section>
</div>
@section Scripts {
    <script src="~/JS/PhysicianDashboard.js?v=1.0.0.2"></script>
}

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/Profile.cshtml
@{
    ViewData["Title"] = "Physician Profile";
}
<header class="py-2">
    <div class="logo"><img src="~/Physician/images/logo.png" /></div>
    <div class="header-heading">Profile</div>
    <div class="user-sec">
        <div class="btn-group">
            <span class="dropdown-toggle user-txt" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Welcome, Walter
            </span>
            <div class="dropdown-menu dropdown-menu-right">
                <button class="dropdown-item" type="button">Requests</button>
                <button class="dropdown-item" type="button">Messages</button>
                <button class="dropdown-item" type="button">Profile</button>
            </div>
        </div>
        <a href="#!" class="logout-txt ml-4">Log out</a>
    </div>
</header>
<div class="header-space"></div>
<div class="container h100">
    <div class="profile-section">
        <div class="col-lg-6 col-md-10 col-12 mx-auto bg-white">
            <div class="row">
                <div class="col-md-6">
                    <div class="py-5 px-4">
                        <div class="profile-title mb-3">Walter Wilson</div>
                        <p class="m-0">Email Address: name@email.com</p>
                        <p class="m-0">Phone Number: 555.555.5555</p>
                        <p class="m-0">Date of Birth: 02-01-85</p>
                    </div>
                </div>
                <div class="col-md-6 d-flex justify-content-center align-items-center">
                    <a href="#!" class="large-teal-btn px-5">Change Password</a>
                </div>
            </div>
        </div>
    </div>
</div>

TylerHendricks-Web/Areas/PhysicianPortal/Views/Home/ResetPassword.cshtml
@model ResetPasswordModel
@{
    ViewData["Title"] = "Physician ResetPassword";
}
<div id="UpdateContentDiv" style="width:100%">
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section class="col-12">
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6">
                    <img src="~/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Reset Password</h3>
                        <input type="hidden" asp-for="TokenId" />
                        <input type="hidden" asp-for="Token" />
                        <form method="post">
                            <div class="form-group">
                                <span asp-validation-for="ChnagePass" class="text-danger"></span>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i><input asp-for="ChnagePass" class="form-control br-0" type="password" id="pass" />
                                </div>
                                <label>Password</label>
                            </div>
                            <div class="form-group">
                                <span asp-validation-for="ConfirmChnagePass" class="text-danger"></span>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i><input asp-for="ConfirmChnagePass" class="form-control br-0" id="confirmPass" type="password" />
                                </div>
                                <label>Confirm Password</label>
                            </div>
                            <button type="submit" class="btn btn-theme btn-block">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>