TylerHendricks-Web/Areas/AdminPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TylerHendricks_Core.Models;
using TylerHendricks_Repo.Contracts;
using TylerHendricks_Utility;
using TylerHendricks_Web.Claim;
using TylerHendricks_Web.Filters;

using static TylerHendricks_Utility.Enums.Areas;

namespace TylerHendricks_Web.Areas.AdminPortal.Controllers
{
    [Area("AdminPortal")]
    public class HomeController : Controller
    {
        private readonly IUsers _userManager;
        private readonly IEmailProvider _email;
        private readonly IUserService _userService;
        private readonly IRepositoryCollection _repCollection;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ILogger<HomeController> _logger;
        private readonly ResourcesConfig _resourcesConfig;
        private readonly EnvironmentalResource _environmentalResource;

        public HomeController(IUsers userManager, IEmailProvider email, IRepositoryCollection repositoryCollection, IUserService
     userService, IWebHostEnvironment hostingEnvironment, ILogger<HomeController> logger, ResourcesConfig resourcesConfig
            ,EnvironmentalResource environmentalResource)
        {
            _userManager = userManager;
            _email = email;
            _repCollection = repositoryCollection;
            _userService = userService;
            _hostingEnvironment = hostingEnvironment;
            _logger = logger;
            _resourcesConfig = resourcesConfig;
            _environmentalResource = environmentalResource;
        }

        #region [User Handler]
        [HttpGet]
        [AllowAnonymous]
        [Route("admin-portal")]
        [ServiceFilter(typeof(CustomLoginedUserAuthentication))]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("admin-portal")]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                loginModel.Role = RoleType.Admin.ToString();
                LoginType loginType = await _userManager.SignIn(loginModel).ConfigureAwait(true);
                if (loginType == LoginType.Success)
                {
                    return RedirectToAction(nameof(PatientInfo), "Home", new { area = PortalType.AdminPortal.ToString() });
                }
                else if (loginType == LoginType.WrongPassword)
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                    return View();
                }
                else
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", _resourcesConfig.ErrorMessageForEmail);
                return View();
            }
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("admin-portal/ForGotPassword")]
        public IActionResult ForGotPassword()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("admin-portal/ForGotPassword")]
        public async Task<IActionResult> ForGotPassword(ForgotModel resetPassword)
        {
            ActionResult action;
            if (ModelState.IsValid)
            {
                resetPassword.Role = RoleType.Admin.ToString();
                PasswordToken passToken = await _userManager.ResetPasswordToken(resetPassword).ConfigureAwait(true);
                if (passToken != null)
                {
                    var PassworfLink = Url.Action(nameof(ResetPassword), "Home", new { area = PortalType.AdminPortal.ToString(), TokenId = passToken.Id, Token = passToken.Token }, Request.Scheme);
                    var htmlbody = await _repCollection.AmazonCustom.GetTemplate
                        ( $"{_environmentalResource.AWSS3Credentials.EmailTemplateDirectory}/{EmailTemplate.ResetPassword.ToString()}.html" 
                        ,_environmentalResource.AWSS3Credentials.BucketName
                        ,_environmentalResource.AWSS3Credentials.AccessKeyId
                        ,_environmentalResource.AWSS3Credentials.SecretAccessKey
                        ).ConfigureAwait(true);
                    List<KeyValuePair<string, string>> placeHolders = new List<KeyValuePair<string, string>>() { new KeyValuePair<string, string>("{{ResetLink}}", PassworfLink) };
                    string body = Comman.UpdatePaceHolder(htmlbody, placeHolders);
                    _email.PlaintTextGmail(EmailTemplate.ResetPassword.ToString(), resetPassword.Email, _resourcesConfig.ResetPasswordEmailSubject, body);
                    TempData["alert"] = AlertType.ForgotPassword;
                    return action = RedirectToAction(nameof(Login));
                }
                else
                {
                    ModelState.AddModelError("", _resourcesConfig.ErrorMessageForUsername);
                    return View();
                }
            }
            else
            {
                return action = RedirectToAction(nameof(ForGotPassword));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ResetPassword(string TokenId, string Token)
        {
            if (string.IsNullOrEmpty(TokenId) || string.IsNullOrEmpty(Token))
            {
                return RedirectToAction(nameof(ForGotPassword), "Home", new { area = PortalType.AdminPortal.ToString() });
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> ResetPassword(ResetPasswordModel resetPassModel)
        {
            ActionResult action;
            if (ModelState.IsValid)
            {
                var IsSuccess = await _userManager.ResetPassword(resetPassModel).ConfigureAwait(true);
                TempData["alert"] = AlertType.ResetPassword;
                if (IsSuccess.Succeeded)
                {
                    action = RedirectToAction(nameof(Login));
                }
                else
                {
                    action = RedirectToAction(nameof(ResetPassword));
                }
            }
            else
            {
                action = RedirectToAction(nameof(ResetPassword));
            }
            return action;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> LogOut()
        {
            await _userManager.SignOut().ConfigureAwait(true);
            return RedirectToAction(nameof(Login), "Home", new { area = PortalType.AdminPortal.ToString() });
        }
        #endregion

        #region [State]

        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> State()
        {
            try
            {
                var serviceStates = await _repCollection.Admin.GetStates().ConfigureAwait(true);
                return View(serviceStates);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveState(int stateId)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false  };
            try
            {
                var result = await _repCollection.Admin.ChangeStateStatus(stateId).ConfigureAwait(true);
                if (result.Succeeded)
                {
                    ajaxResponse.Succeeded = true;
                }
            }
            catch (Exception ex)
            {
                ajaxResponse.Succeeded = false;
                ajaxResponse.ErrorMessage = ex.Message;
            }
            return Json(ajaxResponse);
        }

        #endregion

        #region [Notification]
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Notification()
        {
            try
            {
                var notifications = await _repCollection.Admin.GetNotifications().ConfigureAwait(true);
                return View(notifications);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveNotification(int id)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false };
            try
            {
                var result = await _repCollection.Admin.ChangeNotificationStatus(id).ConfigureAwait(true);
                if (result.Succeeded)
                {
                    ajaxResponse.Succeeded = true;
                }
            }
            catch (Exception ex)
            {
                ajaxResponse.Succeeded = false;
                ajaxResponse.ErrorMessage = ex.Message;
            }
            return Json(ajaxResponse);
        }
        #endregion

        #region [Consultation]
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Consultation()
        {
            try
            {
                var consultations =  await _repCollection.Admin.GetConsultations().ConfigureAwait(true);
                return View(consultations);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> ActiveInActiveConsultation(int id)
        {
            var ajaxResponse = new AjaxResponse() { Succeeded = false };
            try
            {

TylerHendricks-Web/Areas/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using TylerHendricks_Core.Models;
using TylerHendricks_Core.ViewModel;
using TylerHendricks_Repo.Contracts;
using TylerHendricks_Web.Claim;
using static TylerHendricks_Utility.Enums.Areas;

namespace TylerHendricks_Web.Areas.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        #region Initialize private field
        private readonly IRepositoryCollection _repoCollection;
        private readonly IUserService _userService;
        private readonly IUsers _userManager;

        #endregion
        public HeaderViewComponent(IRepositoryCollection repoCollection, IUserService userService, IUsers userManager)
        {
            _repoCollection = repoCollection;
            _userService = userService;
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync(bool ShowRightSection, bool ShowQuestions, bool StaticHeading, string HeadingText,int QuestionId=0)
        {
            var sessionManager = _userService.GetSeesionvalue<SessionManager>(SessionKey.SessionManager.ToString());
            ViewBag.StaticHeading = StaticHeading;
            ViewBag.QuestionId = QuestionId;
            if (StaticHeading)
            {
                ViewBag.HeadingText = HeadingText;
            }
            ViewBag.userName = User.Identity.Name;
            var userId = _userService.GetUserId();
            ViewBag.userId = userId;
            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                ViewBag.ConsultationStatus = await _repoCollection.Patients.UserConsultationStatus(userId).ConfigureAwait(true);
                if (ViewBag.ConsultationStatus)
                {
                    ViewBag.userName = await _userManager.GetFirstName(User.Identity.Name).ConfigureAwait(true);
                }
            }
            if (sessionManager != null)
            {
                ViewBag.ConsultationCategoryId = sessionManager.ConsultationCategoryId;
            }
            else
            {
                ViewBag.ConsultationCategoryId = 0;
            }
            if (ShowQuestions)
            {
                ViewBag.TotalQuestion = await _repoCollection.Patients.TotalQuestions(sessionManager.ConsultationCategoryId).ConfigureAwait(true);
                if (userId != null)
                {
                    ViewBag.TottalAttempt = await _repoCollection.Patients.AttemptQuestions(userId, sessionManager.ConsultationCategoryId, sessionManager.ConsultationId).ConfigureAwait(true);
                }
                else
                {
                    ViewBag.TottalAttempt = 1;
                }
            }
            ViewBag.ShowRightSection = ShowRightSection;
            ViewBag.ShowQuestions = ShowQuestions;
            return View();
        }
    }
}

TylerHendricks-Web/Areas/PatientPortal/Views/Home/ExitConsultation.cshtml
@model Questions
@{
    ViewData["Title"] = "ExitConsultation";
}

@await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
<section class="col-12 select-wrapper">
    <div class="container-fluid">
        <div class="row signIn">
            <div class="col-md-12 mt-2 text-center text-md-left pl-0">
                <a class="pre select-state-iconmargin ml-0" asp-action="StartConsultation" asp-controller="Home" asp-area="PatientPortal">
                    <img src="~/Images/arrow-alt.png" alt=""> Previous
                </a>
            </div>
            <div class="col-12 d-flex align-items-center flex-column">
                <div class="col-3"></div>
                <div class="d-flex justify-content-around flex-column mt-3">
                    <p class="text-center midContent">
                        @Html.Raw(Model.Description)
                    </p>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
    </div>
</section>

TylerHendricks-Web/Areas/PatientPortal/Views/Home/FinishYourConsultation.cshtml
@inject IRepositoryCollection _repoCollection
@model SessionManager
@{
    ViewData["Title"] = "finish Consultation Category";
   // var listConsultations = await _repoCollection.Patients.GetConsultations();
}
@await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = true, HeadingText = "FINISH YOUR CONSULTATION" })
<section class="col-12">
    <div class="container">
        <div class="row mainQs">
            <div class="col-12 d-flex align-items-center flex-column">
                <form method="post">
                    <input type="hidden" id="hidConsultationId" asp-for="ConsultationCategoryId" />
                    <div class="d-flex justify-content-around flex-column mt-5 pt-5">
                        <h2 class="text-center font-weight-bold pb-4" style="color: #16213f">WELCOME BACK</h2>
                    </div>
                    <div class="category-button-2">
                        <div class="btn-theme2 btn-block btn-height60 bg-darkgray home-btn">
                            <button type="submit" onclick="SetConsulationType(3)" class="consultant-type-2">
                                <img src="/Images/user.png" class="img-consultanttype" />
                                FINISH YOUR HAIR LOSS CONSULTATION
                            </button>
                        </div>
                        <br />
                        <div class="btn-theme2 btn-block btn-height60 bg-golden home-btn">
                            <button type="submit" onclick="SetConsulationType(2)" class="consultant-type-2">
                                <img src="/Images/medication.png" class="img-consultanttype" />
                             FINISH YOUR MEDICATION REFILL CONSULTATION
                            </button>
                        </div>
                        <br />
                        <div class="btn-theme2 btn-block btn-height60 bg-trtoise home-btn">
                            <button type="submit" onclick="SetConsulationType(1)" class="consultant-type-2">
                                <img src="/Images/icon - erectile dysfunction.png" class="img-consultanttype" />
                               FINISH YOUR ERECTILE DYSFUNCTION CONSULTATION
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

TylerHendricks-Web/Areas/PatientPortal/Views/Home/ForGotPassword.cshtml
@model ForgotModel
@{
    ViewData["Title"] = "FogotPassword";
}
<div id="UpdateContentDiv" style="width:100%">

    @await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section>
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6">
                    <img src="~/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex loginbg">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Forgot Password</h3>
                        <form method="post">
                            <div class="form-group">
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i>
                                    <input asp-for="Email" class="form-control br-0 pl-4" type="text" />
                                </div>
                                <label>Email Address</label>
                            </div>
                            <button type="submit" class="btn btn-theme btn-block">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section Scripts
            {
<script src="~/JS/Login.js"></script>
            }

TylerHendricks-Web/Areas/PatientPortal/Views/Home/Login.cshtml
@model LoginModel
@{
    ViewData["Title"] = "Patient Login";
}
<div id="UpdateContentDiv" style="width:100%">
    @await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section>
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6">
                    <img src="~/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex loginbg">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Patient Log In</h3>
                        <form id="" method="post" asp-action="Login" asp-controller="Home" asp-area="PatientPortal">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i><input asp-for="Email" class="form-control br-0 pl-4 pr-4" type="text" />
                                </div>
                                <label>Email Address</label>
                            </div>
                            <div class="form-group">
                                <div class="inputControl position-relative">
                                    <i class="fa fa-lock position-absolute" aria-hidden="true"></i><input asp-for="Password" class="form-control br-0 pl-4 pr-4" type="password" />
                                </div>
                                <label>Password</label>
                            </div>
                            <input type="hidden" asp-for="TimezoneOffSet" id="hdnTimeZone" />
                            <input type="hidden" asp-for="IsDayLightSaving" id="hdnDayLightSaving" />
                            <button type="submit" onclick="SetTimeZone();" class="btn btn-theme btn-block">Log In</button>
                            <a asp-action="ForGotPassword" asp-controller="Home" asp-area="PatientPortal">Forgot your password?</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section Scripts
{
    <script src="~/JS/Login.js?v=1.0.0.0"></script>
}

TylerHendricks-Web/Areas/PatientPortal/Views/Home/NotifyPatient.cshtml
@model Notify
@{
    ViewData["Title"] = "Notify Page";
}
@await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })

<section class="col-12 select-wrapper">
    <div class="container-fluid">
        <div class="row mainQs">
            <div class="col-md-12 mt-2 text-center text-md-left pl-0 mob-t5 mob-b5">
                <a class="pre select-state-iconmargin ml-0" asp-controller="Home" asp-action="SelectState" asp-area="PatientPortal">
                    <img src="/Images/arrow-alt.png" /> Previous
                </a>
            </div>
            <div class="col-12  d-flex align-items-center flex-column">
                <form method="post">
                    <div class="d-flex justify-content-around flex-column">
                        @if (!Convert.ToBoolean(ViewBag.isRecordSvae))
                        {
                            <p class="text-center midContent fs-12">
                                <span>Hendrx Health is currently not servicing your state.</span><br />
                                <span>If you would like to be notified once we are available</span><br />
                                <span>in your state please provide your email below.</span>
                            </p>
                            <input type="text" asp-for="Email" class="form-control br-0" placeholder="enter email address" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                            <input type="hidden" asp-for="StateId" value="@ViewBag.StateId" />
                            <div class="text-center mt-4">
                                <button type="submit" class="btn-theme2 notify-btn btn-block">Yes, please notify me</button>
                            </div>
                        }
                        else
                        {
                            <p class="text-center midContent p-notify">
                                <span>Thank you for your submission.</span><br />
                                <span>We look forward to servicing you in the future.</span>
                            </p>
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

TylerHendricks-Web/Areas/PatientPortal/Views/Home/ResetPassword.cshtml
@model ResetPasswordModel
@{
    ViewData["Title"] = "ResetPassword";
}
<div id="UpdateContentDiv" style="width:100%">
    @await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
    <input type="hidden" value="@TempData["alert"]" id="hiddenAlert" />
    <section>
        <div class="container-fluid">
            <div class="row patientLogin">
                <div class="col-md-6">
                    <img src="~/Images/logo.png" />
                </div>
                <div class="col-md-6 d-flex loginbg">
                    <div class="patientLogInDetails">
                        <h3 class="text-center headingText">Reset Password</h3>
                        <input type="hidden" asp-for="TokenId" />
                        <input type="hidden" asp-for="Token" />
                        <form method="post">
                            <div class="form-group">
                                <span asp-validation-for="ChnagePass" class="text-danger"></span>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i>
                                    <input asp-for="ChnagePass" class="form-control br-0 pl-4" type="password" id="pass" />
                                </div>
                                <label>Password</label>
                            </div>
                            <div class="form-group">
                                <span asp-validation-for="ConfirmChnagePass" class="text-danger"></span>
                                <div class="inputControl position-relative">
                                    <i class="fa fa-user position-absolute" aria-hidden="true"></i>
                                    <input asp-for="ConfirmChnagePass" class="form-control br-0 pl-4" id="confirmPass" type="password" />
                                </div>
                                <label>Confirm Password</label>
                            </div>
                            <button type="submit" class="btn btn-theme btn-block">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section Scripts
{
    <script src="~/JS/Login.js"></script>
}

TylerHendricks-Web/Areas/PatientPortal/Views/Home/SelectState.cshtml
@inject IRepositoryCollection _repoCollection
@model SessionManager
@{
    ViewData["Title"] = "State selection";
    var listState = await _repoCollection.States.GetStates();
}
@await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
<section class="col-12 select-wrapper">
    <div class="container-fluid">
        <div class="row mainQs">
            <div class="col-md-12 mt-2 mb-5 text-center text-md-left pl-0">
                <a class="pre select-state-iconmargin ml-0" asp-controller="Home" asp-action="Index" asp-area="PatientPortal">
                    <img src="~/Images/arrow-alt.png" alt="">Previous
                </a>
            </div>
            <div class="col-12 mt-5 d-flex align-items-center flex-column">
                <form method="post" class="selectstate-button">
                    <div class="d-flex justify-content-around flex-column">
                        <p class="text-center">In which state are you currently?</p>
                        <div class="wrap">
                            <select class="select-rel form-control br-0 input-bg" onchange="SelectStateDropdownChange(this)" asp-for="StateId" asp-items="@(new SelectList(listState,"Id","StateName"))">
                                <option value="0"></option>
                            </select>
                        </div>
                        <span id="SelectSelectionErrorMessage" asp-validation-for="StateId" class="pt-1 span-danger text-danger text-center"></span>
                        <div class="text-center  mt-4">
                            <button type="submit" class="btn-font s-center btn-theme2 btn-block">Next</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/JS/Common.js?v=1.0.0.0"></script>
}

TylerHendricks-Web/Areas/PatientPortal/Views/Home/StartConsultation.cshtml
@model Questions
@{
    ViewData["Title"] = "Consultation";
}

@await Component.InvokeAsync("Header", new { ShowRightSection = false, ShowQuestions = false, StaticHeading = false, HeadingText = "" })
<section class="col-12 select-wrapper">
    <div class="container-fluid">
        <div class="row mainQs">
            <div class="col-md-12 mt-2 mb-4 text-center text-md-left pl-0">
                <a class="pre select-state-iconmargin ml-0" asp-controller="Home" asp-action="SelectState" asp-area="PatientPortal">
                    <img src="~/Images/arrow-alt.png" alt=""> Previous
                </a>
            </div>
            <div class="col-12 d-flex align-items-center flex-column">
                <form method="post">
                    <div class="d-flex justify-content-around flex-column mt-5" style="width:100%">
                        <p class="text-center midContent">
                            @Html.Raw(Model.Description)
                        </p>
                        <div class="text-center w90 row">
                            <input type="hidden" asp-for="Id" value="@Model.Id" />
                            <input type="hidden" asp-for="Response" id="hdnResponse" value="@Model.Response" />
                            <input type="hidden" asp-for="NextQuestionId" id="hdNextQuestion" value="@Model.NextQuestionId" />
                            <input type="hidden" asp-for="PreviousQuestionId" id="hdPrevQuestion" value="@Model.PreviousQuestionId" />
                            <input type="hidden" asp-for="Answer" id="hdAnswer" value="@Model.Answer" />
                            <input type="hidden" asp-for="ConsultationCategoryId" value="@Model.ConsultationCategoryId" />

                            <div class="btnWrap d-flex justify-content-center w-100 btn-wrp">
                                <button type="submit" class="btn-theme2 fs-22 mr-2" id="btn-pd" onclick="SetResponseDef(this, true,@Model.NextQuestionId);">YES</button>
                                <button type="submit" class="btn-theme2 fs-22 mr-2 btn-mr" onclick="SetResponseDef(this, false,@Model.NextQuestionId1);">NO
                                    
                                    
                                    @*<html>
                                    <head>
                                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                                        <script>
                                            $(document).ready(function () {
                                                $("#hide").click(function () {
                                                    $("NO").hide();
                                                });
                                                $("#show").click(function () {
                                                    $("YES").show();
                                                });
                                            });
                                        </script>
                                    </head>
                                   
                                    </html>*@


                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <script>
        function SetResponseDef(current, response, questionId) {
            $('#hdnResponse').val(response);
            $('#hdNextQuestion').val(questionId);
            $('#hdAnswer').val($(current).html());
        }
    </script>
}